teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.3
        offset: -0.03
      -
        axis: 0
        target: angular.z
        scale: 0.3
      -
        axis: 2
        target: linear.y
        scale: 0.3